import slicer

[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/15310195-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/15310195-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3114290-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3114290-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3114290-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3114290-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3114290-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3114290-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3114290-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3114290-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3381601-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3381601-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/3381601-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/3381601-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4030409-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4030409-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4030409-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4030409-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4201242-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4201242-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4201242-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4201242-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4201242-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4201242-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4201242-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4201242-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4494251-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4494251-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4494251-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4494251-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4586390-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4586390-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4586390-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4586390-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4631837-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4631837-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4631837-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4631837-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4698863-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4698863-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4698863-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4698863-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4698863-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4698863-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4698863-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4698863-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4842255-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4842255-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4842255-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4842255-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4867376-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4867376-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4867376-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4867376-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4867376-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4867376-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4867376-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4867376-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4886842-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4886842-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/4886842-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/4886842-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5118042-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5118042-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5118042-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5118042-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5120345-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5120345-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5120345-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5120345-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5120345-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5120345-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5120345-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5120345-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5132284-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5132284-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5132284-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5132284-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5152906-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5152906-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5152906-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5152906-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5237749-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5237749-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5237749-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5237749-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5237749-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5237749-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5237749-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5237749-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5257445-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5257445-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5257445-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5257445-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5273136-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5273136-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5273136-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5273136-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5346350-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5346350-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5346350-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5346350-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5440801-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5440801-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5440801-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5440801-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5466148-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5466148-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5466148-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5466148-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5480265-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5480265-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5480265-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5480265-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5494647-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5494647-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5494647-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5494647-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5519749-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5519749-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5519749-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5519749-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5616129-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5616129-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5616129-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5616129-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5634450-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5634450-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5634450-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5634450-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5634450-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5634450-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5634450-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5634450-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5746820-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5746820-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5746820-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5746820-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5766808-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5766808-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5766808-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5766808-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5811664-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5811664-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5811664-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5811664-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5821652-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5821652-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5821652-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5821652-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5862368-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5862368-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5862368-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5862368-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5874713-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5874713-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5874713-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5874713-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5928846-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5928846-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5928846-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5928846-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5946238-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5946238-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5946238-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5946238-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5946238-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5946238-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/5946238-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/5946238-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-3/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-3/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6040625-3/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6040625-3/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6055038-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6055038-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6055038-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6055038-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6156679-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6156679-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6156679-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6156679-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6202182-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6202182-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6202182-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6202182-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6203696-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6203696-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6203696-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6203696-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6234965-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6234965-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6234965-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6234965-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6235347-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6235347-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6235347-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6235347-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6266567-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6266567-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6266567-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6266567-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6301764-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6301764-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6301764-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6301764-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6329655-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6329655-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6329655-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6329655-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6510934-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6510934-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6510934-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6510934-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6510934-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6510934-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6510934-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6510934-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6513536-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6513536-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6513536-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6513536-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6532364-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6532364-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6532364-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6532364-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6538624-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6538624-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6538624-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6538624-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6563226-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6563226-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6563226-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6563226-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6588657-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6588657-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6588657-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6588657-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6652962-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6652962-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6652962-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6652962-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6675198-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6675198-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6675198-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6675198-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6680799-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6680799-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6680799-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6680799-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6687488-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6687488-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6687488-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6687488-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6781919-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6781919-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6781919-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6781919-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6854181-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6854181-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6854181-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6854181-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-1/T2/14 t2_haste_tra_p2_ct.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-1/T2/14 t2_haste_tra_p2_ct.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-2/T2/14 t2_haste_tra_p2_ct.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-2/T2/14 t2_haste_tra_p2_ct.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880988-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880988-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880990-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880990-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6880990-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6880990-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6901669-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6901669-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6901669-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6901669-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6979576-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6979576-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6979576-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6979576-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6979576-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6979576-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/6979576-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/6979576-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7003254-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7003254-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7003254-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7003254-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7010567-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7010567-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7010567-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7010567-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7021255-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7021255-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7021255-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7021255-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7021255-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7021255-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7021255-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7021255-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7034304-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7034304-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7034304-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7034304-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7076038-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7076038-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7076038-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7076038-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7093520-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7093520-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7093520-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7093520-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7093520-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7093520-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7093520-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7093520-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7215216-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7215216-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7215216-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7215216-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7296536-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7296536-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7296536-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7296536-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7388073-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7388073-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7388073-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7388073-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7405297-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7405297-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7405297-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7405297-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7443518-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7443518-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7443518-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7443518-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7483392-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7483392-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7483392-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7483392-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7515426-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7515426-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7515426-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7515426-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7524839-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7524839-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7524839-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7524839-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7524839-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7524839-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7524839-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7524839-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7628900-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7628900-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7628900-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7628900-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7628900-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7628900-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7628900-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7628900-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7652635-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7652635-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7652635-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7652635-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7679571-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7679571-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7679571-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7679571-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7692229-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7692229-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7692229-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7692229-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7710536-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7710536-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7710536-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7710536-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7710536-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7710536-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7710536-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7710536-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7711646-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7711646-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7711646-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7711646-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7711646-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7711646-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7711646-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7711646-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7714201-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7714201-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7714201-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7714201-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7730362-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7730362-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7730362-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7730362-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7730362-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7730362-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7730362-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7730362-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7768353-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7768353-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7768353-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7768353-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7805680-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7805680-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7805680-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7805680-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7827484-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7827484-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7827484-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7827484-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7925386-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7925386-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7925386-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7925386-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7977040-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7977040-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7977040-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7977040-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7980518-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7980518-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7980518-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7980518-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7980518-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7980518-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/7980518-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/7980518-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8048091-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8048091-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8048091-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8048091-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8048091-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8048091-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8048091-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8048091-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8181978-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8181978-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8181978-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8181978-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8181978-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8181978-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8181978-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8181978-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8195736-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8195736-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8195736-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8195736-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8195736-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8195736-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8195736-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8195736-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8234746-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8234746-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8234746-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8234746-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8400708-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8400708-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8400708-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8400708-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8523943-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8523943-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8523943-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8523943-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8523943-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8523943-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8523943-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8523943-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8648334-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8648334-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8648334-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8648334-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8805435-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8805435-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8805435-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8805435-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8832387-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8832387-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8832387-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8832387-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8833270-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8833270-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8833270-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8833270-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8929226-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8929226-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8929226-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8929226-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8934579-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8934579-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8934579-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8934579-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8966545-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8966545-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/8966545-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/8966545-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9007060-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9007060-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9007060-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9007060-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9007060-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9007060-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9007060-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9007060-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9013029-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9013029-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9013029-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9013029-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9013029-2/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9013029-2/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9013029-2/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9013029-2/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9023898-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9023898-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9023898-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9023898-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9033903-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9033903-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9033903-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9033903-1/T2/segMask_tumor.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9116815-1/T2/imagingVolume.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9116815-1/T2/imagingVolume.nii")
[success, loadedVolumeNode] = slicer.util.loadVolume("C:/Users/Robin/Downloads/raw2/9116815-1/T2/segMask_tumor.nrrd", returnNode=True)
slicer.util.saveNode(loadedVolumeNode, "C:/Users/Robin/Downloads/raw2/9116815-1/T2/segMask_tumor.nii")